### ISSUE TITLE
cmd

### ISSUE THREAD

**Issue by Jean-Baptiste-Lasselle** [ricard-io/setup-website#1]
```Yaml
restart: always
    command: hugo serve --watch --baseURL http://127.0.0.1:1313/ --bind 0.0.0.0 -p 1313
    # entrypoint: bash
```
