### ISSUE TITLE
retrieved lost code

### ISSUE THREAD

**Issue by Jean-Baptiste-Lasselle** [ricard-io/setup-website#2]
```Yaml
      - run:
          name: "Container images build for the CMS env."
          command: |
            echo "Checking Circle CI Job env. variables"
            source .cms.env
            echo "QUAY_OCI_IMAGE_TAG=[${QUAY_OCI_IMAGE_TAG}]"
            export GIT_COMMIT_ID=$(git rev-parse --short HEAD)
            export CICD_BUILD_ID=$CIRCLE_BUILD_NUM
            export CICD_BUILD_TIMESTAMP=$(date --rfc-3339 seconds)
            echo "GIT_COMMIT_ID=${GIT_COMMIT_ID}" | tee -a .cms.env
            echo "CICD_BUILD_ID=${CICD_BUILD_ID}" | tee -a .cms.env
            echo "CICD_BUILD_TIMESTAMP=${CICD_BUILD_TIMESTAMP}" | tee -a .cms.env
            docker-compose -f ./docker-compose.build.yml build hugo_heroku
            # and now [quay.io/ricardio/website:${QUAY_OCI_IMAGE_TAG}] should exists among [docker images]
            docker images

      - run:
          name: "Container images push to Quay.io for the CMS image"
          command: |
            echo "Checking Circle CI Job env. variables"
            echo "SECRETHUB_ORG=[${SECRETHUB_ORG}]"
            echo "SECRETHUB_REPO=[${SECRETHUB_REPO}]"
            QUAY_BOT_USERNAME=$(secrethub read ${SECRETHUB_ORG}/${SECRETHUB_REPO}/ricard_io_bot/oci/quay-io/user-name)
            QUAY_BOT_SECRET=$(secrethub read ${SECRETHUB_ORG}/${SECRETHUB_REPO}/ricard_io_bot/oci/quay-io/user-pwd)
            echo "QUAY_BOT_USERNAME=[${QUAY_BOT_USERNAME}]"
            # echo "QUAY_BOT_SECRET=[${QUAY_BOT_SECRET}]"
            docker login -u="${QUAY_BOT_USERNAME}" -p="${QUAY_BOT_SECRET}" quay.io
            source .cms.env
            echo "QUAY_OCI_IMAGE_TAG=[${QUAY_OCI_IMAGE_TAG}]"
            echo "GIT_COMMIT_ID=[${GIT_COMMIT_ID}]"
            echo "CICD_BUILD_ID=[${CICD_BUILD_ID}]"
            echo "CICD_BUILD_TIMESTAMP=[${CICD_BUILD_TIMESTAMP}]"
            docker tag "quay.io/ricardio/website:${QUAY_OCI_IMAGE_TAG}" "quay.io/ricardio/website:${QUAY_OCI_IMAGE_TAG}-latest"
            docker push "quay.io/ricardio/website:${QUAY_OCI_IMAGE_TAG}"
            docker push "quay.io/ricardio/website:${QUAY_OCI_IMAGE_TAG}-latest"

      - run:
          name: "Container images build for the Heroku Deployment: Hugo Build (checking no hugo build error occurs)"
          command: |
            echo "Checking Circle CI Job env. variables"
            export GIT_RELEASE_TAG=$(git describe --tags --abbrev=0)
            export QUAY_OCI_IMAGE_TAG=${GIT_RELEASE_TAG}-heroku
            echo "QUAY_OCI_IMAGE_TAG=[${QUAY_OCI_IMAGE_TAG}]"
            export GIT_COMMIT_ID=$(git rev-parse --short HEAD)
            export CICD_BUILD_ID=$CIRCLE_BUILD_NUM
            export CICD_BUILD_TIMESTAMP=$(date --rfc-3339 seconds)
            echo "GIT_COMMIT_ID=${GIT_COMMIT_ID}" | tee .heroku.env
            echo "CICD_BUILD_ID=${CICD_BUILD_ID}" | tee .heroku.env
            echo "CICD_BUILD_TIMESTAMP=${CICD_BUILD_TIMESTAMP}" | tee .heroku.env
            source .heroku.env
            docker-compose -f ./docker-compose.build.yml build hugo_heroku
            # and now [quay.io/ricardio/website:${QUAY_OCI_IMAGE_TAG}] should exists among [docker images]
            docker images

      - run:
          name: "Container images push to Quay.io for the Heroku Deployment"
          command: |
            echo "Checking Circle CI Job env. variables"
            echo "SECRETHUB_ORG=[${SECRETHUB_ORG}]"
            echo "SECRETHUB_REPO=[${SECRETHUB_REPO}]"
            QUAY_BOT_USERNAME=$(secrethub read ${SECRETHUB_ORG}/${SECRETHUB_REPO}/ricard_io_bot/oci/quay-io/user-name)
            QUAY_BOT_SECRET=$(secrethub read ${SECRETHUB_ORG}/${SECRETHUB_REPO}/ricard_io_bot/oci/quay-io/user-pwd)
            echo "QUAY_BOT_USERNAME=[${QUAY_BOT_USERNAME}]"
            # echo "QUAY_BOT_SECRET=[${QUAY_BOT_SECRET}]"
            docker login -u="${QUAY_BOT_USERNAME}" -p="${QUAY_BOT_SECRET}" quay.io
            export GIT_RELEASE_TAG=$(git describe --tags --abbrev=0)
            export QUAY_OCI_IMAGE_TAG=${GIT_RELEASE_TAG}-heroku
            docker tag "quay.io/ricardio/website:${QUAY_OCI_IMAGE_TAG}" "quay.io/ricardio/website:stable-latest"
            echo "checking [date time] (sometimes data time in Circle CI pipelines is wrong, so that Container registry rejects the [docker push]...)"
            echo "date time in Circle CI Pipeline is [$(date)] "
            date
            docker push "quay.io/ricardio/website:${QUAY_OCI_IMAGE_TAG}"
            docker push "quay.io/ricardio/website:stable-latest"
```

**Comment by Jean-Baptiste-Lasselle** [comment]
* `.cms.env`
```
ALPINE_OCI_IMAGE_TAG=3.13
GOLANG_VERSION=1.15.6
HUGO_VERSION=0.78.2
QUAY_OCI_IMAGE_TAG=cms
```
* `.heroku.env` : 
```
ALPINE_OCI_IMAGE_TAG=3.13
GOLANG_VERSION=1.15.6
HUGO_VERSION=0.78.2
QUAY_OCI_IMAGE_TAG=cms
bash-3.2$ cat .heroku.env 
HTTPD_OCI_IMAGE_TAG=2.4
ALPINE_OCI_IMAGE_TAG=3.13
GOLANG_VERSION=1.15.6
HUGO_VERSION=0.78.2
HUGO_BASE_URL=https://ricard-io.herokuapp.com/
```

**Comment by Jean-Baptiste-Lasselle** [comment]
```Yaml
  hugo_cms:
    # we need extended, and nodejs for sass!
    image: quay.io/ricardio/website:${QUAY_OCI_IMAGE_TAG}
    container_name: hugo_cms
    build:
       context: .
       dockerfile: cms.Dockerfile
       args:
         - ALPINE_OCI_IMAGE_TAG=${ALPINE_OCI_IMAGE_TAG}
         - GOLANG_VERSION=${GOLANG_VERSION}
         - HUGO_VERSION=${HUGO_VERSION}
         - GIT_COMMIT_ID=${GIT_COMMIT_ID}
         - CICD_BUILD_ID=${CICD_BUILD_ID}
         - CICD_BUILD_TIMESTAMP=${CICD_BUILD_TIMESTAMP}
    env_file:
      - ./.cms.env
  hugo_heroku:
    image: quay.io/ricardio/website:${QUAY_OCI_IMAGE_TAG}
    container_name: hugo_heroku
    build:
       context: .
       dockerfile: heroku.Dockerfile
       args:
         - HTTPD_OCI_IMAGE_TAG=${HTTPD_OCI_IMAGE_TAG}
         - ALPINE_OCI_IMAGE_TAG=${ALPINE_OCI_IMAGE_TAG}
         - GOLANG_VERSION=${GOLANG_VERSION}
         - HUGO_VERSION=${HUGO_VERSION}
         - HUGO_BASE_URL=${HUGO_BASE_URL}
         - GIT_COMMIT_ID=${GIT_COMMIT_ID}
         - CICD_BUILD_ID=${CICD_BUILD_ID}
         - CICD_BUILD_TIMESTAMP=${CICD_BUILD_TIMESTAMP}
    env_file:
      - ./.heroku.env
```
